apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "photon.fullname" . }}
  labels:
    {{- include "photon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "photon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "photon.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}                    
          command:
            - "/bin/bash"
            - "-c"
            - {{- toYaml .Values.photon.entrypoint | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Values.storage.volumeName }}
              mountPath: {{ .Values.storage.subPath | quote }}   
      volumes:
        - name: {{ .Values.storage.volumeName }}
          persistentVolumeClaim:
            claimName: "{{ .Values.storage.persistentClaimName }}"
