{{- if .Values.storage.create }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.storage.persistentName | default (include "photon.fullname" .) }}"
  labels:
    type: {{ .Values.storage.persistentType | quote }}
spec: 
  storageClassName: {{ .Values.storage.storageClass | quote }}
  capacity:
    storage: {{ .Values.storage.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
{{- end }}