apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: redis
    version: 18.0.1
    repo: https://charts.bitnami.com/bitnami
    releaseName: redis
    valuesFile: redis-values.yaml
