apiVersion: batch/v1
kind: Job
metadata:
  name: photon-job-download-search-indexes
  # @Important: to make it working it must be the same namespace as nfs-server
  namespace: shared
spec:
  template:
    spec:
      containers:
      - name: photon-index
        image: alpine:latest
        securityContext:
          runAsUser: 0
          runAsNonRoot: false
        command:
          - sh
          - -c
          - |
            echo "Download elasticsearch indexes..."
            apk --no-cache add curl tar
            
            # Download ES indexes
            curl -L https://download1.graphhopper.com/public/extracts/by-country-code/ad/photon-db-ad-latest.tar.bz2 | tar -xj --strip-components=1 -C elasticsearch/
            
            # Set permissions
            chown -R 1000:1000 ./elasticsearch
            chmod -R 777 ./elasticsearch

            echo "Done"
        volumeMounts:
        - name: nfs
          mountPath: /elasticsearch
      restartPolicy: Never
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs
