image:
  # repository: tonsnoei/photon-geocoder  # local image
  repository: tazo90/photon
  pullPolicy: IfNotPresent
  tag: "1.0.14"

service:
  port: 2322

storage:
  volumeName: "nfs"
  persistentClaimName: "nfs"
  subPath: "photon"

photon:
  # data_dir: "/photon/photon_data"
  entrypoint: |
    # Run with external elasticsearch
    java -jar photon.jar -cluster elastic -transport-addresses elasticsearch-master-hl.shared.svc:9300 -languages en

