apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      initContainers:
        - name: allow-to-write-by-non-roots
          image: busybox
          command:
            - sh
            - -c
            - |
              chown -R 1000:1000 /exports
              chmod -R 777 /exports
          volumeMounts:
          - name: nfs-pvc
            mountPath: /exports
      containers:
        - name: nfs-server
          image: k8s.gcr.io/volume-nfs:0.8
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          volumeMounts:
            - name: nfs-pvc
              mountPath: /exports
      volumes:
        - name: nfs-pvc
          persistentVolumeClaim:
            claimName: nfs
