apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shared

resources:
  - 01-deployment.yaml
  - 02-service.yaml
  - 03-pv.yaml
  - 04-pvc.yaml
  # - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/deploy/example/nfs-provisioner/nfs-server.yaml
