apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        imagePullPolicy: IfNotPresent
        securityContext:
          readOnlyRootFilesystem: true
        envFrom:
        - configMapRef:
            name: postgres-config
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres", "-h", "localhost"]
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres", "-h", "localhost"]
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
      restartPolicy: Always
