apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Kustomization
namespace: postgres

resources:
  - namespace.yaml

helmCharts:
  - name: postgres
    version: 15.4.0
    repo: https://charts.bitnami.com/bitnami
    releaseName: postgres
    namespace: postgres
    valuesFile: postgres-values.yaml