apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: postgresql
    version: 12.10.0
    repo: https://charts.bitnami.com/bitnami
    releaseName: postgres
    valuesFile: postgres-values.yaml