apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "valhalla.fullname" . }}
  labels:
    {{- include "valhalla.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "valhalla.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "valhalla.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "valhalla.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TILE_URLS
              value: {{ quote .Values.valhalla.tile_urls }}
            - name: SERVER_THREADS
              value: {{ quote .Values.valhalla.server_threads }}
            - name: SERVE_TILES
              value: {{ quote .Values.valhalla.serve_tiles }}
            - name: USE_TILES_IGNORE_PFB
              value: {{ quote .Values.valhalla.use_tiles_ignore_pbf }}
            - name: TILESET_NAME
              value: {{ quote .Values.valhalla.tileset_name }}
            - name: BUILD_ELEVATION
              value: {{ quote .Values.valhalla.build_elevation }}
            - name: BUILD_ADMINS
              value: {{ quote .Values.valhalla.build_admins }}
            - name: BUILD_TIME_ZONES
              value: {{ quote .Values.valhalla.build_time_zones }}
            - name: BUILD_TRANSIT
              value: {{ quote .Values.valhalla.build_transit }}
            - name: BUILD_TAR
              value: {{ quote .Values.valhalla.build_tar }}
            - name: FORCE_REBUILD
              value: {{ quote .Values.valhalla.force_rebuild }}            
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
