apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "valhalla.fullname" . }}
  labels:
    {{- include "valhalla.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "valhalla.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "valhalla.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "valhalla.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: tile_urls
              value: {{ .Values.valhalla.tile_urls | quote }}
            - name: server_threads
              value: {{ .Values.valhalla.server_threads | quote }}
            - name: serve_tiles
              value: {{ .Values.valhalla.serve_tiles | quote }}
            - name: use_tiles_ignore_pbf
              value: {{ .Values.valhalla.use_tiles_ignore_pbf | quote }}
            - name: tileset_name
              value: {{ .Values.valhalla.tileset_name | quote }}
            - name: build_elevation
              value: {{ .Values.valhalla.build_elevation | quote }}
            - name: build_admins
              value: {{ .Values.valhalla.build_admins | quote }}
            - name: build_time_zones
              value: {{ .Values.valhalla.build_time_zones | quote }}
            - name: build_transit
              value: {{ .Values.valhalla.build_transit | quote }}
            - name: build_tar
              value: {{ .Values.valhalla.build_tar | quote }}
            - name: force_rebuild
              value: {{ .Values.valhalla.force_rebuild | quote }}    
          volumeMounts:
            - name: {{ .Values.storage.volumeName }}
              mountPath: {{ .Values.storage.subPath | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: {{ .Values.storage.volumeName }}
          persistentVolumeClaim:
            claimName: "{{ .Values.storage.persistentClaimName }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
