app: 
  key: 255d861b-5ea1-5996-9aa3-922530ec40b1
  secret: 6116487b-cda1-52c2-b5b5-c8022c45e263
  telemetry: false

admin:
  email: admin@example.com
  password: directus

db:
  client: pg
  host: postgres-postgresql.postgres.svc
  port: 5432
  dbname: testdb
  user: dbuser
  password: dbpass

cache:
  enabled: true
  store: redis
  uri: redis://:test123@redis-master.redis.svc:6379

service:
  port: 8055

env:
  - name: LOG_LEVEL
    value: "info"
