kind: Kustomization
namespace: directus

resources:
  - namespace.yaml

helmGlobals:
  chartHome: ./charts

helmCharts:
- name: directus
  version: 10.6.1
  releaseName: directus
  namespace: directus
  valuesFile: directus-values.yaml
