apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: rabbitmq
    version: 11.1.4
    repo: https://charts.bitnami.com/bitnami
    releaseName: rabbitmq
    valuesFile: rabbitmq-values.yaml
