resources:
  # Databases
  - ../../../components/postgres
  - ../../../components/redis
  # Services
  - ../../../components/nominatim
  - ../../../components/photon  

commonLabels:
  app: gishere

# namePrefix: gishere-

