apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  # ../components/nginx-ingress
  # ../componebts/sentry
  - ../components/nfs-server
  - ../components/argocd
  - ../components/postgres
  - ../components/redis
  - ../components/elasticsearch

patches:
  - path: patches/postgres-values.yaml
    target:
      kind: ConfigMap
      name: postgres-postgresql-init-scripts
