apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ../components/nginx-ingress
  # ../componebts/sentry  
  - ../components/argocd
  - ../components/postgres
  - ../components/redis

patches:
  - path: patches/postgres-values.yaml
    target:
      kind: ConfigMap
      name: postgres-postgresql-init-scripts
