clusterName: "elastic"

image:
  tag: 7.17.14-debian-11-r0

master:
  masterOnly: false
  replicaCount: 1
  # nameOverride: "photon"

data:
  replicaCount: 0

coordinating:
  replicaCount: 0

ingest:
  enabled: false

service:
  type: NodePort
