clusterName: "elastic"

image:
  #tag: 7.17.14-debian-11-r0
  # @important: on ES 6 and older has been changed indexes. Use v5 to keep compatibility.
  tag: 5.6.16

master:
  masterOnly: false
  replicaCount: 1

  persistence: 
    enabled: false

  extraVolumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: nfs

  extraVolumeMounts:
    - name: nfs
      # mountPath: /exports/elasticsearch/data
      mountPath: /elasticsearch

  # Force run as root
  # containerSecurityContext:
  #   runAsUser: 0
  #   runAsNonRoot: false
  # nameOverride: "photon"

data:
  replicaCount: 0

coordinating:
  replicaCount: 0

ingest:
  enabled: false

service:
  type: NodePort

# initContainers:
# - name: install
#   image: alpine:latest
#   command: 
#     - sh
#     - -c
#     - |
#       echo "Download elasticsearch indexes..."
#       apk --no-cache add curl tar
#       curl -L https://download1.graphhopper.com/public/extracts/by-country-code/ad/photon-db-ad-latest.tar.bz2 | tar -xj --strip-components=2 -C /bitnami/elasticsearch/
#       # wget --user-agent="docker: tonsnoei/photon-geocoder" -O - https://download1.graphhopper.com/public/extracts/by-country-code/ad/photon-db-ad-latest.tar.bz2 | bzip2 -cd > /workdir/photon-db-ad-latest.tar
#   volumeMounts:
#     - name: shared-volume
#       mountPath: "/bitnami/elasticsearch"

persistence:
  enabled: false

# extraEnvs:
#   - name: path.data
#     value: /exports/elasticsearch/data

esConfig:
  elasticsearch.yml: |
    path.data: /exports/elasticsearch/data

# extraVolumes:
#   - name: nfs

# extraVolumeMounts:
#   - name: nfs
#     mountPath: /exports/elasticsearch/data


volumePermissions:
  enabled: true


# persistence:
#   enabled: false

# extraVolumes:
#   - name: nfs

# extraVolumeMounts:
#   - name: nfs
#     mountPath: /elasticsearch
