clusterName: "elastic"

image:
  #tag: 7.17.14-debian-11-r0
  # @important: on ES 6 and older has been changed indexes. Use v5 to keep compatibility.
  tag: 5.6.16

master:
  masterOnly: false
  replicaCount: 1
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false

  persistence: 
    enabled: false

  extraVolumes:
    - name: nfs
      persistentVolumeClaim:
        claimName: nfs

  extraVolumeMounts:
    - name: nfs
      mountPath: /bitnami/

  extraEnvVars:
    - name: path.data
      value: "/bitnami/elasticsearch/"

  # Force run as root
  # containerSecurityContext:
  #   runAsUser: 0
  #   runAsNonRoot: false
  # nameOverride: "photon"

data:
  replicaCount: 0

coordinating:
  replicaCount: 0

ingest:
  enabled: false

service:
  type: NodePort


volumePermissions:
  enabled: true
