kind: Kustomization
namespace: elasticsearch

resources:
  - namespace.yaml

helmGlobals:
  chartHome: ./charts

helmCharts:
  - name: elasticsearch
    version: 19.11.3
    repo: https://charts.bitnami.com/bitnami
    releaseName: elasticsearch
    namespace: elasticsearch
    valuesFile: elasticsearch-values.yaml