kind: Kustomization
namespace: shared

helmGlobals:
  chartHome: ./charts

helmCharts:
  - name: elasticsearch
    version: 19.11.3
    repo: https://charts.bitnami.com/bitnami
    releaseName: elasticsearch
    namespace: shared
    valuesFile: elasticsearch-values.yaml
