kind: Kustomization

helmGlobals:
  chartHome: ./charts

helmCharts:
  - name: nominatim
    version: 3.9.1
    repo: https://robjuz.github.io/helm-charts/
    releaseName: nominatim
    valuesFile: nominatim-values.yaml